language: bash

services:
  - docker

before_install:
  - echo "before install"

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "begin to build docker image"

after_success:
  - docker build -t csp_test:v1.0 .
  - docker tag csp_test:v1.0 summergift/csp_test:v1.0
  - docker push summergift/csp_test:v1.0
